---
  - name: Add required repos
    sudo: yes
    apt_repository: repo={{ item }} state=present
    with_items:
      - ppa:webupd8team/sublime-text-3
      - ppa:webupd8team/atom

  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - atom
      - sublime-text-installer
      - vim
      - tmux
      - git
      - vim
      - tmux
      - git
      - zsh

  - name: Update apt again
    sudo: yes
    apt:  update_cache=yes

  - name: Download Chrome
    sudo: no
    shell: curl -o chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: Install Chrome
    sudo: yes
    apt: deb=chrome.deb

  - name: Download RCM
    sudo: no
    shell: curl -o rcm.deb https://thoughtbot.github.io/rcm/debs/rcm_1.2.3-1_all.deb

  - name: Install RCM
    sudo: yes
    apt: deb=rcm.deb

  - name: Download Oh-My-ZSH
    sudo: no
    shell: curl -o omzsh.sh https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh

  - name: Install dotfiles
    sudo: no
    shell: git clone git://github.com/thoughtbot/dotfiles.git

  - name: Install dotfiles
    sudo: no
    shell: env RCRC=./dotfiles/rcrc rcup


