---

  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - vim
      - tmux
      - git
      - zsh

  - name: Update apt again
    sudo: yes
    apt:  update_cache=yes

  - name: Download RCM
    sudo: no
    shell: curl -o rcm.deb https://thoughtbot.github.io/rcm/debs/rcm_1.2.3-1_all.deb

  - name: Install RCM
    sudo: yes
    apt: deb=rcm.deb

  - name: Install dotfiles
    sudo: no
    shell: git clone git://github.com/thoughtbot/dotfiles.git

  - name: Install dotfiles
    sudo: no
    shell: env RCRC=./dotfiles/rcrc rcup


